spring:
  application:
    name: papersplease
  
  datasource:
    url: jdbc:postgresql://se.ifmo.ru:5432/studs
    username: ${DB_USERNAME:s335116}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          time_zone: UTC
    open-in-view: false
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    default-property-inclusion: non_null

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: ${JWT_SECRET:default-secret-key-please-change-in-production}
  expiration: 86400000

logging:
  level:
    root: INFO
    com.arekalov.papersplease: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  writer-with-default-pretty-printer: true
  paths-to-match: /api/v1/**
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs.groups.enabled: true

